anticheat:
  anti-xray:
    enabled: true
    engine-mode: 2

    max-chunk-section-index: 3
    update-radius: 2

    hidden-blocks:
      - diamond_ore
      - deepslate_diamond_ore
      - emerald_ore
      - deepslate_emerald_ore
      - gold_ore
      - deepslate_gold_ore
      - iron_ore
      - deepslate_iron_ore
      - ancient_debris

    replacement-blocks:
      - stone
      - deepslate
      - netherrack
