disable-out-of-border-teleport: true

worlds:
  world:
    border_size: 20000
    center_x: 0
    center_z: 0

  world_nether:
    border_size: 2500
    center_x: 0
    center_z: 0

  world_the_end:
    border_size: 20000
    center_x: 0
    center_z: 0